In [19]:
import pandas as pd
import numpy as np
import plotly.express as px

In [20]:
df1 = pd.read_csv('Store and Staff Performance')
df1.head()

,store_id,first_name,last_name,total_rental_processed,total_revenue_collected,num_unique_customer_served,avg_rentals_per_day
0,2,Jon,Stephens,7385,8376494.49,273,61094.090909
1,1,Mike,Hillyer,7207,9985024.66,326,71235.939394

In [21]:
profitable_store = df1.groupby('store_id')['total_revenue_collected'].max()
print(profitable_store)

store_id
1    9985024.66
2    8376494.49
Name: total_revenue_collected, dtype: float64

In [22]:
df1.sort_values(by='num_unique_customer_served', ascending=False)

,store_id,first_name,last_name,total_rental_processed,total_revenue_collected,num_unique_customer_served,avg_rentals_per_day
1,1,Mike,Hillyer,7207,9985024.66,326,71235.939394
0,2,Jon,Stephens,7385,8376494.49,273,61094.090909

In [23]:
df2 = pd.read_csv('Geographic and Market Analysis dataset')
df2.head()

          country         city  total_rentals  total_revenue  unique_customers
0  United Kingdom       London             46         174.54                 2
1          Runion  Saint-Denis             45         211.55                 1
2   United States   Cape Coral             42         208.58                 1
3   United States       Aurora             42         159.58                 2
4         Belarus    Molodetno             40         189.60                 1

In [36]:
total_revenue_by_country = df2.groupby('country')['total_revenue'].sum().sort_values(ascending=False)
print(total_revenue_by_country)

country
India                               6032.79
China                               5247.04
United States                       3694.27
Japan                               3121.52
Mexico                              2984.82
                                     ...
Afghanistan                           67.82
Tonga                                 64.84
Saint Vincent and the Grenadines      64.82
Lithuania                             63.78
American Samoa                        47.85
Name: total_revenue, Length: 108, dtype: float64

In [25]:
df2.sort_values(by='total_revenue', ascending=False).head(10)

,country,city,total_rentals,total_revenue,unique_customers
1,Runion,Saint-Denis,45,211.55,1
2,United States,Cape Coral,42,208.58,1
6,Brazil,Santa Brbara dOeste,39,194.61,1
8,Netherlands,Apeldoorn,38,191.62,1
4,Belarus,Molodetno,40,189.60,1
10,Iran,Qomsheh,37,183.63,1
0,United Kingdom,London,46,174.54,2
24,United States,Memphis,33,167.67,1
9,Canada,Richmond Hill,38,167.62,1
7,Philippines,Tanza,39,166.61,1

In [26]:
df2.sort_values(by= 'total_rentals', ascending=False).head(10)

,country,city,total_rentals,total_revenue,unique_customers
0,United Kingdom,London,46,174.54,2
1,Runion,Saint-Denis,45,211.55,1
2,United States,Cape Coral,42,208.58,1
3,United States,Aurora,42,159.58,2
4,Belarus,Molodetno,40,189.60,1
5,Taiwan,Changhwa,39,149.61,1
6,Brazil,Santa Brbara dOeste,39,194.61,1
7,Philippines,Tanza,39,166.61,1
8,Netherlands,Apeldoorn,38,191.62,1
9,Canada,Richmond Hill,38,167.62,1

In [27]:
df3 = pd.read_csv('Customer Behaviour and Rentention Dataset')
df3.head()

,first_name,last_name,country,city,total_amount_spent,total_no_of_rentals,first_rental_date,most_recent_rental_date,num_of_rental_months
0,Eleanor,Hunt,Runion,Saint-Denis,4654.10,990,2005-07-06 07:45:13,2005-07-31 19:37:58,7
1,Karl,Seal,United States,Cape Coral,3963.02,798,2005-07-06 05:59:44,2005-07-31 18:21:08,7
2,Eleanor,Hunt,Runion,Saint-Denis,3807.90,810,2005-08-01 23:18:06,2005-08-23 05:57:04,8
3,Rhonda,Kennedy,Netherlands,Apeldoorn,3640.78,722,2005-07-06 04:30:18,2005-07-31 23:40:11,7
4,Marion,Snyder,Brazil,Santa Brbara dOeste,3502.98,702,2005-07-08 21:31:22,2005-07-31 21:33:03,7

In [28]:
repeat_customers = df3[df3['total_no_of_rentals'] > 1]

repeat_percentage = (len(repeat_customers) / len(df3)) * 100

print(f"{repeat_percentage:.2f}% of customers are repeat renters")

100.00% of customers are repeat renters

In [29]:
average_spending = df3['total_amount_spent'].mean()
print(f"Average spending per customer: ${average_spending:.2f}")

Average spending per customer: $691.62

In [30]:
df3['first_rental_date'] = pd.to_datetime(df3['first_rental_date'])
df3['most_recent_rental_date'] = pd.to_datetime(df3['most_recent_rental_date'])

df3['avg_gap_days'] = (df3['most_recent_rental_date'] - df3['first_rental_date']).dt.days / (df3['total_no_of_rentals'] - 1)
df3['avg_gap_days'] = df3['avg_gap_days'].fillna(0)

overall_avg_gap = df3['avg_gap_days'].mean()

print(f"Average time gap between rentals: {overall_avg_gap:.2f} days")

Average time gap between rentals: 0.06 days

In [41]:
churn_threshold_days = 180  

reference_date = df3['most_recent_rental_date'].max()

df3['is_churn_risk'] = (
    (reference_date - df3['most_recent_rental_date']).dt.days > churn_threshold_days
)

num_churn_risk = df3['is_churn_risk'].sum()
total_customers = len(df3)

churn_rate = num_churn_risk / total_customers
df3.head()

,first_name,last_name,country,city,total_amount_spent,total_no_of_rentals,first_rental_date,most_recent_rental_date,num_of_rental_months,avg_gap_days,is_churn_risk
0,Eleanor,Hunt,Runion,Saint-Denis,4654.10,990,2005-07-06 07:45:13,2005-07-31 19:37:58,7,0.025278,True
1,Karl,Seal,United States,Cape Coral,3963.02,798,2005-07-06 05:59:44,2005-07-31 18:21:08,7,0.031368,True
2,Eleanor,Hunt,Runion,Saint-Denis,3807.90,810,2005-08-01 23:18:06,2005-08-23 05:57:04,8,0.025958,False
3,Rhonda,Kennedy,Netherlands,Apeldoorn,3640.78,722,2005-07-06 04:30:18,2005-07-31 23:40:11,7,0.034674,True
4,Marion,Snyder,Brazil,Santa Brbara dOeste,3502.98,702,2005-07-08 21:31:22,2005-07-31 21:33:03,7,0.032810,True

In [ ]:
df1.to_csv("Store_and_staff_performance.csv", index=False)

In [ ]:
df2.to_csv("Geographic_and_market_analysis.csv", index=False)

In [ ]:
df3.to_csv("Customer_behaviour_and_retention_dataset.csv", index=False)